# Generated by Django 6.0.5 on 2026-05-24 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_customer', models.CharField(max_length=100)),
                ('nama_customer', models.CharField(max_length=120)),
                ('daerah', models.CharField(max_length=150)),
                ('alamat_lengkap', models.TextField()),
                ('no_hp', models.CharField(max_length=30)),
                ('metode_pembayaran', models.CharField(default='COD', max_length=50)),
                ('catatan', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu'), ('diproses', 'Diproses'), ('selesai', 'Selesai')], default='menunggu', max_length=20)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=150)),
                ('kategori', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('harga', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stok', models.PositiveIntegerField(default=0)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('seller_name', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_produk', models.CharField(max_length=150)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=120)),
                ('username_customer', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
